# Problem 11

I will firstly compute QR decompostion by hands. Then I will write a code and check my QR decomposition:

# (a)

$
A
=
\begin{pmatrix}3&-1\\ 4&3\end{pmatrix}
\rightarrow
\vec{u_1}
=
\begin{pmatrix}3\\ 4\end{pmatrix}
;
\vec{u_2}
=
\begin{pmatrix}-1\\ 3\end{pmatrix};
\\\\
$

Let $\vec{u_1} = \vec{v_1} = \begin{pmatrix}3\\ 4\end{pmatrix}$.

Then:

$
\\
\vec{v_2} = \vec{u_2} - proj_{\vec{v_1}}\vec{u_2}
= 
\vec{u_2} - \frac{\vec{u_2} \cdot \vec{v_1}}{\vec{v_1} \cdot \vec{v_1}}\vec{v_1}
=
\\
=
\begin{pmatrix}-1\\ 3\end{pmatrix}
-
\frac{\begin{pmatrix}-1&3\end{pmatrix}\begin{pmatrix}3\\ 4\end{pmatrix}}{\begin{pmatrix}3&4\end{pmatrix}\begin{pmatrix}3\\ 4\end{pmatrix}}\begin{pmatrix}3\\ 4\end{pmatrix}
=
\begin{pmatrix}-1\\ 3\end{pmatrix}
-
\frac{9}{25}
\begin{pmatrix}3\\ 4\end{pmatrix}
=
\begin{pmatrix}-1\\ 3\end{pmatrix}
-
\begin{pmatrix}\frac{27}{25}\\ \frac{36}{25}\end{pmatrix}
=
\begin{pmatrix}-\frac{52}{25}\\ \frac{39}{25}\end{pmatrix}
$

Normalizing $\vec{v_1}$ and $\vec{v_2}$ to $\vec{v_1^{'}}$ and $\vec{v_2^{'}}$:

$
\\
\vec{v_1^{'}}
=
\frac{\vec{v_1}}{||\vec{v_1}||}
=
\frac{\vec{v_1}}{5}
=
\begin{pmatrix}\frac{3}{5}\\ \frac{4}{5}\end{pmatrix};
$

$
\\
\vec{v_2^{'}}
=
\frac{\vec{v_2}}{||\vec{v_2}||}
=
\begin{pmatrix}-\frac{52}{25}\\ \frac{39}{25}\end{pmatrix}
\frac{5}{13}
=
\begin{pmatrix}-\frac{4}{5}\\ \frac{3}{5}\end{pmatrix}
$

Thus:

$
Q
=
\begin{pmatrix}\frac{3}{5}&-\frac{4}{5}\\ \frac{4}{5}&\frac{3}{5}\end{pmatrix}
$

$
R
=
Q^T A
=
\begin{pmatrix}\frac{3}{5}&\frac{4}{5}\\ \:-\frac{4}{5}&\frac{3}{5}\end{pmatrix}\begin{pmatrix}3&-1\\ \:4&3\end{pmatrix}
=
\begin{pmatrix}5&\frac{9}{5}\\ 0&\frac{13}{5}\end{pmatrix}$

$
Q R
=
\begin{pmatrix}\frac{3}{5}&-\frac{4}{5}\\ \frac{4}{5}&\frac{3}{5}\end{pmatrix}\begin{pmatrix}5&\frac{9}{5}\\ 0&\frac{13}{5}\end{pmatrix}
=
\begin{pmatrix}3&-1\\ 4&3\end{pmatrix}
=
A
$

# (b)

$
A
=
\begin{pmatrix}1&2\\ 2&1\\ 2&4\end{pmatrix}
\rightarrow
\vec{u_1}
=
\begin{pmatrix}1\\ 2\\ 2\end{pmatrix}
;
\vec{u_2}
=
\begin{pmatrix}2\\ 1\\ 4\end{pmatrix};
\\\\
$

Let $\vec{u_1} = \vec{v_1} = \begin{pmatrix}1\\ 2\\ 2\end{pmatrix}$.

Then:

$
\\
\vec{v_2} = \vec{u_2} - proj_{\vec{v_1}}\vec{u_2}
= 
\vec{u_2} - \frac{\vec{u_2} \cdot \vec{v_1}}{\vec{v_1} \cdot \vec{v_1}}\vec{v_1}
=
\\
=
\begin{pmatrix}2\\ 1\\ 4\end{pmatrix}
-
\:\frac{\begin{pmatrix}2&1&4\end{pmatrix}\begin{pmatrix}1\\ 2\\ 2\end{pmatrix}}{\begin{pmatrix}1&2&2\end{pmatrix}\begin{pmatrix}1\\ 2\\ 2\end{pmatrix}}\begin{pmatrix}1\\ \:2\\ \:2\end{pmatrix}
=
\begin{pmatrix}2\\ 1\\ 4\end{pmatrix}
-
\begin{pmatrix}\frac{4}{3}\\ \frac{8}{3}\\ \frac{8}{3}\end{pmatrix}
=
\begin{pmatrix}\frac{2}{3}\\ -\frac{5}{3}\\ \frac{4}{3}\end{pmatrix}
=
\vec{v_2};
$

Normalizing $\vec{v_1}$ and $\vec{v_2}$ to $\vec{v_1^{'}}$ and $\vec{v_2^{'}}$:

$
\\
\vec{v_1^{'}}
=
\frac{\vec{v_1}}{||\vec{v_1}||}
=
\frac{\vec{v_1}}{3}
=
\begin{pmatrix}\frac{1}{3}\\ \frac{2}{3}\\ \frac{2}{3}\end{pmatrix};
$

$
\\
\vec{v_2^{'}}
=
\frac{\vec{v_2}}{||\vec{v_2}||}
=
\frac{\vec{v_2}}{\sqrt{5}}
=
\begin{pmatrix}\frac{2}{3}\\ -\frac{5}{3}\\ \frac{4}{3}\end{pmatrix}
\frac{1}{\sqrt{5}}
=
\begin{pmatrix}\frac{2}{3\sqrt{5}}\\ -\frac{5}{3\sqrt{5}}\\ \frac{4}{3\sqrt{5}}\end{pmatrix}
$

Thus:

$
Q
=
\begin{pmatrix}\frac{1}{3}&\frac{2}{3\sqrt{5}}\\ \frac{2}{3}&-\frac{5}{3\sqrt{5}}\\ \frac{2}{3}&\frac{4}{3\sqrt{5}}\end{pmatrix}
$

$
R
=
Q^T A
=
\begin{pmatrix}\frac{1}{3}&\frac{2}{3}&\frac{2}{3}\\ \frac{2}{3\sqrt{5}}&-\frac{5}{3\sqrt{5}}&\frac{4}{3\sqrt{5}}\end{pmatrix}
\begin{pmatrix}1&2\\ 2&1\\ 2&4\end{pmatrix}
=
\begin{pmatrix}3&4\\ 0&\sqrt{5}\end{pmatrix}
$

$
Q R
=
\begin{pmatrix}\frac{1}{3}&\frac{2}{3\sqrt{5}}\\ \frac{2}{3}&-\frac{5}{3\sqrt{5}}\\ \frac{2}{3}&\frac{4}{3\sqrt{5}}\end{pmatrix}\begin{pmatrix}3&4\\ 0&\sqrt{5}\end{pmatrix}
=
\begin{pmatrix}1&2\\ 2&1\\ 2&4\end{pmatrix}
=
A
$

# (c)

$
A
=
\begin{pmatrix}1&2&2\\ 2&-1&1\\ 2&0&1\end{pmatrix};
\vec{u_1}
=
\begin{pmatrix}1\\ 2\\ 2\end{pmatrix}
;
\vec{u_2}
=
\begin{pmatrix}2\\ -1\\ 0\end{pmatrix};
\vec{u_3}
=
\begin{pmatrix}2\\ 1\\ 1\end{pmatrix};
\\\\
$

Let $\vec{u_1} = \vec{v_1} = \begin{pmatrix}1\\ 2\\ 2\end{pmatrix}$.


Then:

$
\\
\vec{v_2} = \vec{u_2} - proj_{\vec{v_1}}\vec{u_2}
= 
\vec{u_2} - \frac{\vec{u_2} \cdot \vec{v_1}}{\vec{v_1} \cdot \vec{v_1}}\vec{v_1}
=
\\
=
\begin{pmatrix}2\\ -1\\ 0\end{pmatrix}
-
\:\frac{\begin{pmatrix}2&-1&0\end{pmatrix}\begin{pmatrix}1\\ 2\\ 2\end{pmatrix}}{\begin{pmatrix}1&2&2\end{pmatrix}\begin{pmatrix}1\\ 2\\ 2\end{pmatrix}}\begin{pmatrix}1\\ \:2\\ \:2\end{pmatrix}
=
\begin{pmatrix}2\\ -1\\ 0\end{pmatrix}
=
\vec{v_2};
$

Then:
$
\\
\vec{v_3} = \vec{u_3} - proj_{\vec{v_1}}\vec{u_3}-proj_{\vec{v_2}}\vec{u_3}
= 
\\
=
\begin{pmatrix}2\\ 1\\ 1\end{pmatrix}
-
\:\frac{\begin{pmatrix}2&1&1\end{pmatrix}\begin{pmatrix}1\\ 2\\ 2\end{pmatrix}}{\begin{pmatrix}1&2&2\end{pmatrix}\begin{pmatrix}1\\ 2\\ 2\end{pmatrix}}\begin{pmatrix}1\\ \:2\\ \:2\end{pmatrix}
-
\:\frac{\begin{pmatrix}2&1&1\end{pmatrix}\begin{pmatrix}2\\ -1\\ 0\end{pmatrix}}{\begin{pmatrix}2&-1&0\end{pmatrix}\begin{pmatrix}2\\ -1\\ 0\end{pmatrix}}\begin{pmatrix}2\\ -1\\ 0\end{pmatrix}
=
\begin{pmatrix}2\\ 1\\ 1\end{pmatrix}
-
\frac{2}{3}
\begin{pmatrix}1\\ \:2\\ \:2\end{pmatrix}
-
\frac{3}{5}
\begin{pmatrix}2\\ -1\\ 0\end{pmatrix}
=
\begin{pmatrix}2\\ 1\\ 1\end{pmatrix}
-
\begin{pmatrix}\frac{2}{3}\\ \frac{4}{3}\\ \frac{4}{3}\end{pmatrix}
-
\begin{pmatrix}\frac{6}{5}\\ -\frac{3}{5}\\ 0\end{pmatrix}
=
\begin{pmatrix}\frac{2}{15}\\ \frac{4}{15}\\ -\frac{1}{3}\end{pmatrix}
=
\vec{v_3}
$

Normalizing $\vec{v_1}$, $\vec{v_2}$,$\vec{v_3}$ to $\vec{v_1^{'}}$, $\vec{v_2^{'}}$, $\vec{v_3^{'}}$:

$
\\
\vec{v_1^{'}}
=
\frac{\vec{v_1}}{||\vec{v_1}||}
=
\frac{\vec{v_1}}{3}
=
\begin{pmatrix}\frac{1}{3}\\ \frac{2}{3}\\ \frac{2}{3}\end{pmatrix};
$

$
\\
\vec{v_2^{'}}
=
\frac{\vec{v_2}}{||\vec{v_2}||}
=
\frac{\vec{v_2}}{\sqrt{5}}
=
\begin{pmatrix}2\\ -1\\ 0\end{pmatrix}
\frac{1}{\sqrt{5}}
=
\begin{pmatrix}\frac{2}{\sqrt{5}}\\ \frac{-1}{\sqrt{5}}\\ 0\end{pmatrix}
$

$
\\
\vec{v_3^{'}}
=
\frac{\vec{v_3}}{||\vec{v_3}||}
=
\frac
{
\begin{pmatrix}\frac{2}{15}\\ \frac{4}{15}\\ -\frac{1}{3}\end{pmatrix}
}
{
\sqrt{\frac{1}{5}}
}
=
\begin{pmatrix}\frac{2}{3\sqrt{5}}\\ \frac{4}{3\sqrt{5}}\\ -\frac{\sqrt{5}}{3}\end{pmatrix}
$

Thus:

$
Q
=
\begin{pmatrix}\frac{1}{3}&\frac{2}{\sqrt{5}}&\frac{2}{3\sqrt{5}}\\ \frac{2}{3}&-\frac{1}{\sqrt{5}}&\frac{4}{3\sqrt{5}}\\ \frac{2}{3}&0&-\frac{\sqrt{5}}{3}\end{pmatrix}
$

$
R
=
Q^T A
=
\begin{pmatrix}\frac{1}{3}&\frac{2}{3}&\frac{2}{3}\\ \frac{2}{\sqrt{5}}&-\frac{1}{\sqrt{5}}&0\\ \frac{2}{3\sqrt{5}}&\frac{4}{3\sqrt{5}}&-\frac{\sqrt{5}}{3}\end{pmatrix}
\begin{pmatrix}1&2&2\\ 2&-1&1\\ 2&0&1\end{pmatrix}
=
\begin{pmatrix}3&0&2\\ 0&\sqrt{5}&\frac{3}{\sqrt{5}}\\ 0&0&\frac{1}{\sqrt{5}}\end{pmatrix}
$

$
Q R
=
\begin{pmatrix}\frac{1}{3}&\frac{2}{\sqrt{5}}&\frac{2}{3\sqrt{5}}\\ \frac{2}{3}&-\frac{1}{\sqrt{5}}&\frac{4}{3\sqrt{5}}\\ \frac{2}{3}&0&-\frac{\sqrt{5}}{3}\end{pmatrix}
\begin{pmatrix}3&0&2\\ 0&\sqrt{5}&\frac{3}{\sqrt{5}}\\ 0&0&\frac{1}{\sqrt{5}}\end{pmatrix}
=
\begin{pmatrix}1&2&2\\ 2&-1&1\\ 2&0&1\end{pmatrix}
=
A
$

# Writing a code (in Python) for the QR-decomposition using the Gram–Schmidt algorithm to check above solutions.

In [28]:
import numpy as np
import sys
import warnings

if not sys.warnoptions:
    warnings.simplefilter("ignore")

Writing function of finding projection of v_2 onto v_1 to use it later in algorithm:

In [15]:
def projection(v1, v2):
    proj = (np.dot(v2, v1) / np.dot(v1, v1)) * v1
    return proj

Writing function of extracting column vectors from an arbitrary given matrix A:

In [16]:
def extract_col_vectors(A):
    col_vectors = []
    for i in range(A.shape[1]):
        col_vectors.append(A[:,i])
    return col_vectors

Writing function that sums given column vectors resulting in vector: 

In [17]:
#summing list of arrays
def sum_arrays(list_arrays):
    first = list_arrays[0]
    sum_list = [first]
    for i in range(1, len(list_arrays)):
        print(list_arrays[i])
        sum_list[0] = np.add(sum_list[0],list_arrays[i])
    return sum_list[0]

Writing Gram-Schmidt process algorithm in one function:

In [32]:
def gram_schmidt_algorithm(A):
    #exctrating column vectors from A using above defined function
    col_vectors = extract_col_vectors(A)
    #creating a list that will be iteratively filled with orthogonal vectors in Gram-Schmidt process
    W = []
    #appending the first vector to W
    W.append(col_vectors[0])
    #looping through the rest of column vectors
    for i in range(1,len(col_vectors)):
        #extracting current col vector
        u = col_vectors[i]
        #base case - when we have just one first vector in our list of orthogonal vectors
        if len(W)==1:
            proj_onto_subspace = projection(W[0],u)
            result = np.subtract(u,proj_onto_subspace)
            W.append(result)
        #for current col vector looping through each of orthogonal vectors in W, finding projection on each of them, adding proj to list
        elif len(W) > 1:
            proj_set = []
            for i in W:
                proj = projection(i,u)
                proj_set.append(proj)
            #adding all projections using above defined function
            proj_onto_subspace = sum_arrays(proj_set)
            #subtracting from current col vector result of projections addition to get our new orthogonal vector and adding it to list W
            result = np.subtract(u,proj_onto_subspace)
            W.append(result)
    #finding orthonormal basis vectors from each vector of our W list:
    orthonormal_basis = []
    for i in W:
        basis = i / np.linalg.norm(i)
        orthonormal_basis.append(basis)
    #stacking our orthonormal vectors together to form Q matrix
    Q = np.column_stack((i for i in orthonormal_basis))
    print('matrix Q is:')
    print(Q)
    print('')
    #finding R matrix
    R = np.dot(Q.T,A)
    print('matrix R is: (without rounding decimals)')
    print(R)
    print('')
    #find QR
    QR = np.dot(Q,R)
    #rounding float values and getting rid of scientific notation in matrice entries
    QR = np.around(QR)
    print('matrix QR is:')
    print(QR)
    print('')
    print('matrix A is:')
    print(A.astype('float'))
    #print('')
    #print('matrices QR and A are equal:', A.astype('float')==QR)
    return Q,R,QR

## Checking (a):

Solution was:

$
Q R
=
\begin{pmatrix}\frac{3}{5}&-\frac{4}{5}\\ \frac{4}{5}&\frac{3}{5}\end{pmatrix}\begin{pmatrix}5&\frac{9}{5}\\ 0&\frac{13}{5}\end{pmatrix}
=
\begin{pmatrix}3&-1\\ 4&3\end{pmatrix}
=
A
$

In [19]:
A = np.array([[3,-1],[4,3]])

In [33]:
Q,R,QR = gram_schmidt_algorithm(A)

matrix Q is:
[[ 0.6 -0.8]
 [ 0.8  0.6]]

matrix R is: (without rounding decimals)
[[ 5.0000000e+00  1.8000000e+00]
 [-4.4408921e-16  2.6000000e+00]]

matrix QR is:
[[ 3. -1.]
 [ 4.  3.]]

matrix A is:
[[ 3. -1.]
 [ 4.  3.]]


Conclusion: We correctly applied Gram-Schmidt in (a). Though, I decided to not round R, so that all computations remain stable.

## Checking (b):

Solution was:

$
Q R
=
\begin{pmatrix}\frac{1}{3}&\frac{2}{3\sqrt{5}}\\ \frac{2}{3}&-\frac{5}{3\sqrt{5}}\\ \frac{2}{3}&\frac{4}{3\sqrt{5}}\end{pmatrix}\begin{pmatrix}3&4\\ 0&\sqrt{5}\end{pmatrix}
=
\begin{pmatrix}1&2\\ 2&1\\ 2&4\end{pmatrix}
=
A
$

In [34]:
A = np.array([[1,2],[2,1],[2,4]])

In [35]:
Q,R,QR = gram_schmidt_algorithm(A)

matrix Q is:
[[ 0.33333333  0.2981424 ]
 [ 0.66666667 -0.74535599]
 [ 0.66666667  0.59628479]]

matrix R is: (without rounding decimals)
[[3.00000000e+00 4.00000000e+00]
 [2.22044605e-16 2.23606798e+00]]

matrix QR is:
[[1. 2.]
 [2. 1.]
 [2. 4.]]

matrix A is:
[[1. 2.]
 [2. 1.]
 [2. 4.]]


Conclusion: We also correctly applied Gram-Schmidt in (b). Though, again,  I decided to not round R, so that all computations remain stable.

## Checking (c):

Solution was:

$
Q R
=
\begin{pmatrix}\frac{1}{3}&\frac{2}{\sqrt{5}}&\frac{2}{3\sqrt{5}}\\ \frac{2}{3}&-\frac{1}{\sqrt{5}}&\frac{4}{3\sqrt{5}}\\ \frac{2}{3}&0&-\frac{\sqrt{5}}{3}\end{pmatrix}
\begin{pmatrix}3&0&2\\ 0&\sqrt{5}&\frac{3}{\sqrt{5}}\\ 0&0&\frac{1}{\sqrt{5}}\end{pmatrix}
=
\begin{pmatrix}1&2&2\\ 2&-1&1\\ 2&0&1\end{pmatrix}
=
A
$

In [37]:
A = np.array([[1,2,2],[2,-1,1],[2,0,1]])

In [38]:
Q,R,QR = gram_schmidt_algorithm(A)

[ 1.2 -0.6  0. ]
matrix Q is:
[[ 0.33333333  0.89442719  0.2981424 ]
 [ 0.66666667 -0.4472136   0.59628479]
 [ 0.66666667  0.         -0.74535599]]

matrix R is: (without rounding decimals)
[[ 3.00000000e+00  0.00000000e+00  2.00000000e+00]
 [ 0.00000000e+00  2.23606798e+00  1.34164079e+00]
 [ 4.44089210e-16 -3.33066907e-16  4.47213595e-01]]

matrix QR is:
[[ 1.  2.  2.]
 [ 2. -1.  1.]
 [ 2.  0.  1.]]

matrix A is:
[[ 1.  2.  2.]
 [ 2. -1.  1.]
 [ 2.  0.  1.]]


Conclusion: We also correctly applied Gram-Schmidt in (c). Though, again,  I decided to not round R, so that all computations remain stable.