In [248]:
import numpy as np

# Home assignment 6. Iteration methods

## Problem 1

$$
A = \begin{pmatrix}2&-1&0\\ -1&2&-1\\ 0&-1&2\end{pmatrix}; b = \begin{pmatrix}1\\ 0\\ 1\end{pmatrix}
$$

In [88]:
A = np.array([[2,-1,0], [-1,2,-1],[0,-1,2]])
b = np.array([1,0,1])

### (a) Solve the system using Gaussian elimination

In [89]:
x = np.linalg.solve(A, b)
print(x)

[1. 1. 1.]


### (b) Determine the D, L, and U matrices of the Jacobi and Gauss–Seidel method and determine the spectral radius of D^-1 (L + U) = B_j and (L + D)^-1 U = B_GS. Comment on whether the Jacobi and Gauss–Seidel methods will always converge.

In [92]:
# Create lower-triangular  matrix from A                                                                                                                                                                                                                                                                                                                     
L = np.tril(A,-1)
# Create diagonal  matrix from A                                                                                                                                                                                                                                                                                                                     
D = np.diag(np.diag(A))
# Create upper-triangular  matrix from A                                                                                                                                                                                                                                                                                                                     
U = np.triu(A,1)

In [93]:
np.add(L,U)

array([[ 0, -1,  0],
       [-1,  0, -1],
       [ 0, -1,  0]])

Spectral radius of a matrix is a maximum absolute value of its eigenvalues. Let's find it.

In [91]:
#let's find spectral radius for D^-1 (L + U) = B_j
B_j = np.dot(np.linalg.inv(D),np.add(L,U))
print('spectral radius of B_j is',max(abs(np.linalg.eigvals(B_j))))

spectral radius of B_j is 0.7071067811865476


In [46]:
#let's find spectral radius for D^-1 (L + D)^-1 U = B_GS
B_GS = np.dot(np.linalg.inv(np.add(L,D)),U)
print('spectral radius of B_GS is',max(abs(np.linalg.eigvals(B_GS))))

spectral radius of B_GS is 0.49999999999999994


The Jacobi and Gauss–Seidel methods will always converge because the maximum absolute value of their B_j and B_GS spectral radiuses is less than 1.

### (c) Perform 10 steps of the Jacobi method starting with x_0 = (0, 0, 0)^T, and evaluate the Euclidean norm of the difference $x_{k+1}-x_k$ of two successive approximate solutions for k=0,1,...,9. Does the decay rate agree with the predicted one based on the spectral radius?

In [16]:
x_0 = np.zeros(3)

In [35]:
def jacobi(A,b,x):
    """Solves equation Ax=b via the Jacobi iterative method
    """
    # Create lower-triangular  matrix from A                                                                                                                                                                                                                                                                                                                     
    L = np.tril(A,-1)
    # Create diagonal  matrix from A                                                                                                                                                                                                                                                                                                                     
    D = np.diag(np.diag(A))
    # Create upper-triangular  matrix from A                                                                                                                                                                                                                                                                                                                     
    U = np.triu(A,1)
    # Calculate matrix B_j
    B_j = -np.dot(np.linalg.inv(D),np.add(L,U))
    # Calculate vector b_j
    b_j = np.dot(np.linalg.inv(D),b)
    #create list of solutions with x_0 already present in it , so that we can compare it with x_1 and so on.
    list_solutions=[x]
    #calculating x_1
    x = np.add(np.dot(B_j,x),b_j)
    #adding x_1 to list of solutions
    list_solutions.append(x)
    #calculating first norm difference x_{k+1}-x_k
    norm_differences=[np.linalg.norm(np.subtract(list_solutions[-1],list_solutions[-2]))]
    #creating list of decay rates (ratios)
    ratios = []
    # Calculate next values
    for i in range(2,10):
        x = np.add(np.dot(B_j,x),b_j)
        list_solutions.append(x)
        ratios.append((np.linalg.norm(np.subtract(list_solutions[-1],list_solutions[-2])))/(np.linalg.norm(np.subtract(list_solutions[-2],list_solutions[-3]))))
        norm_differences.append(np.linalg.norm(np.subtract(list_solutions[-1],list_solutions[-2])))
    return ratios,norm_differences
    #print('Norm of difference between two successive solutions: ',np.linalg.norm(np.subtract(list_solutions[-1],list_solutions[-2])))

In [36]:
ratios,norm_differences = jacobi(A,b,x_0)

#### Euclidean norm of the difference $x_{k+1}-x_k$ of two successive approximate solutions for k=0,1,...,9:

In [37]:
for i in norm_differences:
    print(i)

0.7071067811865476
0.5
0.3535533905932738
0.25
0.1767766952966369
0.125
0.08838834764831845
0.0625
0.04419417382415922


We see that norm differences are decreasing, which means that we are converging to solution.

#### Does the decay rate agree with the predicted one based on the spectral radius?

In [38]:
for i in ratios:
    print(i)

0.7071067811865475
0.7071067811865476
0.7071067811865475
0.7071067811865476
0.7071067811865475
0.7071067811865476
0.7071067811865475
0.7071067811865476


Given that our predicted decay rate, based on spectral radius, is 0.7071067, we see that all 8 decay rates (ratios computed from $\frac{||x_{k+1} - x_{k}||}{||x_{k} - x_{k-1}||}$) are exactly equal to our predicted rate.

### (d) Perform 10 steps of the Gauss-Seidel method starting with x_0 = (0, 0, 0)^T, and evaluate the Euclidean norm of the difference $x_{k+1}-x_k$ of two successive approximate solutions for k=0,1,...,9. Does the decay rate agree with the predicted one based on the spectral radius?

We will exactly do the same as in (c):

In [39]:
x_0 = np.zeros(3)

In [40]:
def gauss_seidel(A,b,x):
    """Solves equation Ax=b via the Jacobi iterative method
    """
    # Create lower-triangular  matrix from A                                                                                                                                                                                                                                                                                                                     
    L = np.tril(A,-1)
    # Create diagonal  matrix from A                                                                                                                                                                                                                                                                                                                     
    D = np.diag(np.diag(A))
    # Create upper-triangular  matrix from A                                                                                                                                                                                                                                                                                                                     
    U = np.triu(A,1)
    #adding x_0 to list of solutions
    list_solutions=[x]
    #calculating x_1
    B_GS_times_x = np.dot(np.dot(-(np.linalg.inv(np.add(L,D))),U),x)
    b_GS = np.dot(np.linalg.inv(np.add(L,D)),b)
    x = np.add(B_GS_times_x,b_GS)
    #adding x_1 to list of solutions
    list_solutions.append(x)
    #calculating first norm difference x_{k+1}-x_k
    norm_differences=[np.linalg.norm(np.subtract(list_solutions[-1],list_solutions[-2]))]
    #creating list of decay rates (ratios)
    ratios = []
    # Calculate next values
    for i in range(2,10):
        B_GS_times_x = np.dot(np.dot(-(np.linalg.inv(np.add(L,D))),U),x)
        b_GS = np.dot(np.linalg.inv(np.add(L,D)),b)
        x = np.add(B_GS_times_x,b_GS)
        list_solutions.append(x)
        ratios.append((np.linalg.norm(np.subtract(list_solutions[-1],list_solutions[-2])))/(np.linalg.norm(np.subtract(list_solutions[-2],list_solutions[-3]))))
        norm_differences.append(np.linalg.norm(np.subtract(list_solutions[-1],list_solutions[-2])))
    return ratios,norm_differences

In [42]:
ratios,norm_differences = gauss_seidel(A,b,x_0)

#### Euclidean norm of the difference $x_{k+1}-x_k$ of two successive approximate solutions for k=0,1,...,9:

In [43]:
for i in norm_differences:
    print(i)

0.8385254915624212
0.4375
0.28125
0.140625
0.0703125
0.03515625
0.017578125
0.0087890625
0.00439453125


We see that norm differences are decreasing, which means that we are converging to solution.

#### Does the decay rate agree with the predicted one based on the spectral radius?

In [45]:
for i in ratios:
    print(i)

0.5217491947499509
0.6428571428571429
0.5
0.5
0.5
0.5
0.5
0.5


Given that our predicted decay rate, based on spectral radius, is 0.4999999, we see that last 6 decay rates (ratios computed from $\frac{||x_{k+1} - x_{k}||}{||x_{k} - x_{k-1}||}$) are approximately equal to our predicted rate.

### (e)  Perform 10 steps of the SOR method using ω = 0.1 and then ω = 1.1 starting with x_0 = (0, 0, 0)^T, and evaluate the Euclidean norm of the difference $x_{k+1}-x_k$ of two successive approximate solutions for k=0,1,...,9. Does the decay rate agree with the predicted one based on the spectral radius?.

Spectral radius of SOR:

In [121]:
A = np.array([[2,-1,0], [-1,2,-1],[0,-1,2]])
L = np.tril(A,-1)
# Create diagonal  matrix from A                                                                                                                                                                                                                                                                                                                     
D = np.diag(np.diag(A))
# Create upper-triangular  matrix from A                                                                                                                                                                                                                                                                                                                     
U = np.triu(A,1)

In [122]:
print('spectral radius of B_GS is for ω=0.1:',max(abs(np.linalg.eigvals((np.dot((np.linalg.inv(np.add(D,0.1*L))),(np.subtract(((1 - 0.1)*D),(0.1*U)))))))))

spectral radius of B_GS is for ω=0.1: 0.9696286079104867


In [123]:
print('spectral radius of B_GS is for ω=1.1:',max(abs(np.linalg.eigvals((np.dot((np.linalg.inv(np.add(D,1.1*L))),(np.subtract(((1 - 1.1)*D),(1.1*U)))))))))

spectral radius of B_GS is for ω=1.1: 0.3785859165294031


In [106]:
x_0 = np.zeros(3)

In [107]:
def SOR(A,b,x,ω):
    """Solves equation Ax=b via the Jacobi iterative method
    """
    # Create lower-triangular  matrix from A                                                                                                                                                                                                                                                                                                                     
    L = np.tril(A,-1)
    # Create diagonal  matrix from A                                                                                                                                                                                                                                                                                                                     
    D = np.diag(np.diag(A))
    # Create upper-triangular  matrix from A                                                                                                                                                                                                                                                                                                                     
    U = np.triu(A,1)
    #adding x_0 to list of solutions
    list_solutions=[x]
    #calculating x_1
    B_SOR_times_x = np.dot((np.dot((np.linalg.inv(np.add(D,ω*L))),(np.subtract(((1 - ω)*D),(ω*U))))),(x))
    b_SOR = ω*np.dot(np.linalg.inv(np.add(D,ω*L)),b)
    x = np.add(B_SOR_times_x,b_SOR)
    #adding x_1 to list of solutions
    list_solutions.append(x)
    #calculating first norm difference x_{k+1}-x_k
    norm_differences=[np.linalg.norm(np.subtract(list_solutions[-1],list_solutions[-2]))]
    #creating list of decay rates (ratios)
    ratios = []
    # Calculate next values
    for i in range(2,10):
        B_SOR_times_x = np.dot((np.dot((np.linalg.inv(np.add(D,ω*L))),(np.subtract(((1 - ω)*D),(ω*U))))),(x))
        b_SOR = ω*np.dot(np.linalg.inv(np.add(D,ω*L)),b)
        x = np.add(B_SOR_times_x,b_SOR)
        list_solutions.append(x)
        ratios.append((np.linalg.norm(np.subtract(list_solutions[-1],list_solutions[-2])))/(np.linalg.norm(np.subtract(list_solutions[-2],list_solutions[-3]))))
        norm_differences.append(np.linalg.norm(np.subtract(list_solutions[-1],list_solutions[-2])))
    return ratios,norm_differences

In [109]:
ratios_w01,norm_differences_w01 = SOR(A,b,x_0,0.1)
ratios_w11,norm_differences_w11 = SOR(A,b,x_0,1.1)

#### For ω = 0.1: 

In [110]:
for i in norm_differences_w01:
    print(i)

0.08381163776588547
0.07039851361456877
0.05924237680859251
0.0499759345835764
0.042292313980117915
0.03593486138373003
0.030688535124398283
0.026372635347273254
0.022834683943908213


We see that norm differences are decreasing, which means that we are converging to solution.

In [111]:
for i in ratios_w01:
    print(i)

0.8399610780929476
0.8415288017719237
0.8435842259510408
0.8462535885025039
0.8496782985348924
0.8540045499742184
0.8593644251955916
0.8658476349906821


We can see that ratio value is slowly approaching spectral radius.

#### For ω = 1.1: 

In [125]:
for i in norm_differences_w11:
    print(i)

0.7314702766517585
0.24450708390252343
0.12162261750143513
0.0352768844865472
0.014441195749375142
0.005358200695882537
0.002039436865611563
0.0007710121300492318
0.0002920033236505023


We see that norm differences are decreasing, which means that we are converging to solution.

In [126]:
for i in ratios_w11:
    print(i)

0.3342679691945014
0.49741960666432833
0.2900520085101025
0.40936709575025754
0.37103580540512937
0.38061972318034865
0.3780514822742647
0.3787272758365771


We can see that ratio value is very close to the spectral radius.

## Problem 2

$$
A = \alpha I + u u^\top, u = (1,-1,1)^\top 
\rightarrow \\
\rightarrow 
u u^\top:
$$

In [47]:
u = np.array([1,-1,1])
uuT = np.outer(u,u)
print(uuT)

[[ 1 -1  1]
 [-1  1 -1]
 [ 1 -1  1]]


$$
\rightarrow
u u^\top = 
\begin{pmatrix}1&-1&1\\ -1&1&-1\\ 1&-1&1\end{pmatrix}
\rightarrow
\\
\rightarrow
A = 
\begin{pmatrix}α&0&0\\ 0&α&0\\ 0&0&α\end{pmatrix}
+
\begin{pmatrix}1&-1&1\\ -1&1&-1\\ 1&-1&1\end{pmatrix}
=
\begin{pmatrix}α+1&-1&1\\ -1&α+1&-1\\ 1&-1&α+1\end{pmatrix}\\
$$

$$
b = u =
\begin{pmatrix}1\\ -1\\ 1\end{pmatrix}\\
$$

$$
Ax = b
\rightarrow
\begin{pmatrix}α+1&-1&1&1\\ -1&α+1&-1&-1\\ 1&-1&α+1&1\end{pmatrix}
$$

### (a) Find a closed form solution (if any) for each real $\alpha$?

$
\begin{pmatrix}α+1&-1&1&1\\ -1&α+1&-1&-1\\ 1&-1&α+1&1\end{pmatrix}
R_2\:\leftarrow \:R_2+\frac{1}{α+1}\cdot \:R_1
=
\begin{pmatrix}α+1&-1&1&1\\ 0&\frac{α^2+2α}{α+1}&-\frac{α}{α+1}&-\frac{α}{α+1}\\ 1&-1&α+1&1\end{pmatrix}
R_3\:\leftarrow \:R_3-\frac{1}{α+1}\cdot \:R_1
=
\begin{pmatrix}α+1&-1&1&1\\ 0&\frac{α^2+2α}{α+1}&-\frac{α}{α+1}&-\frac{α}{α+1}\\ 0&-\frac{α}{α+1}&\frac{α^2+2α}{α+1}&\frac{α}{α+1}\end{pmatrix}
\:R_2\:\leftrightarrow \:R_3
=
\begin{pmatrix}α+1&-1&1&1\\ 0&-\frac{α}{α+1}&\frac{α^2+2α}{α+1}&\frac{α}{α+1}\\ 0&\frac{α^2+2α}{α+1}&-\frac{α}{α+1}&-\frac{α}{α+1}\end{pmatrix}
R_3\:\leftarrow \:R_3-\left(-α-2\right)\cdot \:R_2
=
\begin{pmatrix}α+1&-1&1&1\\ 0&-\frac{α}{α+1}&\frac{α^2+2α}{α+1}&\frac{α}{α+1}\\ 0&0&α\left(α+3\right)&α\end{pmatrix}
R_3\:\leftarrow \frac{1}{α\left(α+3\right)}\cdot \:R_3
=
\begin{pmatrix}α+1&-1&1&1\\ 0&-\frac{α}{α+1}&\frac{α^2+2α}{α+1}&\frac{α}{α+1}\\ 0&0&1&\frac{1}{α+3}\end{pmatrix}
R_2\:\leftarrow \:R_2-\frac{α^2+2α}{α+1}\cdot \:R_3
=
\begin{pmatrix}α+1&-1&1&1\\ 0&-\frac{α}{α+1}&0&\frac{α}{\left(α+1\right)\left(α+3\right)}\\ 0&0&1&\frac{1}{α+3}\end{pmatrix}
\:R_1\:\leftarrow \:R_1-1\cdot \:R_3
=
\begin{pmatrix}α+1&-1&0&\frac{α+2}{α+3}\\ 0&-\frac{α}{α+1}&0&\frac{α}{\left(α+1\right)\left(α+3\right)}\\ 0&0&1&\frac{1}{α+3}\end{pmatrix}
R_2\:\leftarrow \:-\frac{α+1}{α}\cdot \:R_2
=
\begin{pmatrix}α+1&-1&0&\frac{α+2}{α+3}\\ 0&1&0&-\frac{1}{α+3}\\ 0&0&1&\frac{1}{α+3}\end{pmatrix}
\:R_1\:\leftarrow \:R_1+1\cdot \:R_2
=
\begin{pmatrix}α+1&0&0&\frac{α+1}{α+3}\\ 0&1&0&-\frac{1}{α+3}\\ 0&0&1&\frac{1}{α+3}\end{pmatrix}
R_1\:\leftarrow \frac{1}{α+1}\cdot \:R_1
=
\begin{pmatrix}1&0&0&\frac{1}{α+3}\\ 0&1&0&-\frac{1}{α+3}\\ 0&0&1&\frac{1}{α+3}\end{pmatrix}
$

**Solution**:

We see that $\alpha$ $\in$ $\mathbb{R}$ in ${(-\infty,-3)\cup(-3,\infty)}$. That's because we can't divide by zero.

### (b) For what 𝛼 do the methods work? Justify your answer by referring to the spectral radius or the norm of the corresponding B.

As we are not told whether to check necessary or sufficient conditions, we will check sufficient for Jacobi and necessary for Gauss-Seidel.

**b.1 Jacobi:**

We know that sufficient condition for Jacobi methods to converge is that corresponding iteration matrix $Bj$ norm being less than 1: 

$|| Bj || < 1$. 

Let's see for what $\alpha$ we have $|| Bj ||_{\infty} < 1$:

$
Bj
=
-D^{-1}(L+U)
=
-\begin{pmatrix}\frac{1}{α+1}&0&0\\ \:\:\:0&\frac{1}{α+1}&0\\ \:\:\:0&0&\frac{1}{α+1}\end{pmatrix}\begin{pmatrix}0&-1&1\\ \:\:\:-1&0&-1\\ \:\:\:1&-1&0\end{pmatrix}
=
\begin{pmatrix}0&\frac{1}{α+1}&-\frac{1}{α+1}\\ \frac{1}{α+1}&0&\frac{1}{α+1}\\ -\frac{1}{α+1}&\frac{1}{α+1}&0\end{pmatrix}
$ 

$|| Bj ||_{\infty} = \max{\sum_{j=1}^{n}| a_{ij} |}$ = $|-\frac{2}{\alpha+1}| \rightarrow$

So, given denominator of $|| Bj ||_{\infty}$, in order for $|| Bj ||_{\infty} <1$ we need :

$\rightarrow \alpha \in \mathbb{R}$ in ${(-\infty,-3)\cup(1,\infty)}$

**b.2 Gauss-Seidel:**

We know that necessary condition for Gauss-Seidel is that spectral radius $p(B_{GS})<1$. We also know from the lecture that spectral radius $p(B_{GS})<1$ if $A$ is row diagonally dominant. 

So, let's check whether A is strictly row diagonally dominant:

Square matrix A is strictly diagonally dominant if, for every row of the matrix, the magnitude of the diagonal entry in a row is larger than sum of the magnitudes of all non-diagonal entries in that row:

$$
| a_{i,i} | > \sum _{j\not=i}\:| a_{i,i} | 
$$
for all $i$, where $a_{ij}$ denotes the entry in the ith row and jth column.
Thus, let's solve for $\alpha$ for every row:
$$
\\
$$
Row 1 : 
$$
\\
| a_{1,1} | = | \alpha +1 |; | a_{1,2} | + | a_{1,3} | = 2
\rightarrow
\\
\rightarrow 
| \alpha + 1 | > 2
\rightarrow
\alpha+1<-2\quad \mathrm{or}\quad \:\alpha+1>2
\rightarrow
\\
\rightarrow
\alpha<-3\quad \mathrm{or}\quad \:\alpha>1.
$$
$$
\\
$$
We can clearly see that the same inequality holds also for all other rows: row 2 and row 3.
$$
$$
Thus, Gauss-Seidel and SOR methods necessary condition for Gauss-Seidel convergence is satisfied when $ \alpha \in \mathbb{R}$ in ${(-\infty,-3)\cup(1,\infty)}$.

### (c) Write the corresponding iteration scheme for Jacobi method starting with $x_0=$*0*. How many iterations are required to achieve 0.001 accuracy? Test three different α in the convergence range. 

Let's check in convergence range for $\alpha > 1$. 

We will use the next formula for measuring accuracy of current iteration in order to check whether we reached stopping criteria $\epsilon$ (which in our case equals 0.001):
$$
\frac{| x_{k}-x_{k-1}  |}{| x_{k} |} < \epsilon
$$

In [98]:
#let's firstly create 'b' vector from Ax=b
b = np.array([1,-1,1])
print(b)

[ 1 -1  1]


In [99]:
def jacobi(𝛼,uuT,b,stopping_criteria=0.001):
    """Solves equation Ax=b via the Jacobi iterative method,where
    𝛼 - parameter alpha of Problem 2 (;
    uuT - outer product of u;
    Instruction:
    we will perform first iteration and other iterations separately,
    because we can't divide by the norm of x_0 as it is a zero vector. Other 
    iterations will be perform via 'while' loop using base case accuracy of 10.
    """
    # Create matrix A from sum of matrix 𝛼I and matrix uu^T (𝛼I + uu^T)
    alpha_times_identity = np.array([[α,0,0],[0,α,0],[0,0,α]])
    A = np.add(alpha_times_identity,uuT)
    # Create lower-triangular  matrix from A                                                                                                                                                                                                                                                                                                                     
    L = np.tril(A,-1)
    # Create diagonal  matrix from A                                                                                                                                                                                                                                                                                                                     
    D = np.diag(np.diag(A))
    # Create upper-triangular  matrix from A                                                                                                                                                                                                                                                                                                                     
    U = np.triu(A,1)
    # Calculate matrix B_j
    B_j = -np.dot(np.linalg.inv(D),np.add(L,U))
    # Calculate vector b_j
    b_j = np.dot(np.linalg.inv(D),b)
    #initial guess
    x = np.zeros(3)
    #first iteration
    x = np.add(np.dot(B_j,x),b_j)
    #creating a list to count lately the number of iterations before reaching a stopping criteria
    list_1=[]
    list_1.append(x)
    #establish a base case accuracy
    acc=10
    #second and other iterations
    while acc >= stopping_criteria:
        #formula for checking out current accuracy: np.linalg.norm(np.add(np.dot(B_j,x),b_j)-x)/np.linalg.norm(x)
        acc = np.linalg.norm(np.add(np.dot(B_j,x),b_j)-x)/np.linalg.norm(x)
        x = np.add(np.dot(B_j,x),b_j)
        list_1.append(x)
    num_iter = len(list_1)
    print('Number of iteration to achieve 0.001 accuracy: ', num_iter)
    print('Found solution is vector: ', x)
    return x, num_iter

Let's now see how many iterations are required to achieve 0.001 accuracy for such choice of 𝛼 as (2,3,4).

In [100]:
for 𝛼 in (2,3,4):
    print('For Alpha coefficient: ', 𝛼)
    x, num_iter = jacobi(𝛼,uuT,b)
    print('')

For Alpha coefficient:  2
Number of iteration to achieve 0.001 accuracy:  20
Found solution is vector:  [ 0.19993985 -0.19993985  0.19993985]

For Alpha coefficient:  3
Number of iteration to achieve 0.001 accuracy:  12
Found solution is vector:  [ 0.16662598 -0.16662598  0.16662598]

For Alpha coefficient:  4
Number of iteration to achieve 0.001 accuracy:  9
Found solution is vector:  [ 0.14289459 -0.14289459  0.14289459]



### (d) Write the corresponding iteration scheme for Gauss-Seidel method starting with $x_0=$*0*. How many iterations are required to achieve 0.001 accuracy? Test three different α in the convergence range. 

We will use the same convergence range ($\alpha>1$) for Gauss-Seidel:

In [260]:
def gauss_seidel(𝛼,uuT,b,stopping_criteria=0.001):
    """Solves equation Ax=b via the Gauss-Seidel iterative method,where
    𝛼 - parameter alpha of Problem 2 (;
    uuT - outer product of u;
    Instruction:
    we will perform first iteration and other iterations separately,
    because we can't divide by the norm of x_0 as it is a zero vector. Other 
    iterations will be perform via 'while' loop using base case accuracy of 10.
    """
    # Create matrix A from sum of matrix 𝛼I and matrix uu^T (𝛼I + uu^T)
    alpha_times_identity = np.array([[α,0,0],[0,α,0],[0,0,α]])
    A = np.add(alpha_times_identity,uuT)
    # Create lower-triangular  matrix from A                                                                                                                                                                                                                                                                                                                     
    L = np.tril(A,-1)
    # Create diagonal  matrix from A                                                                                                                                                                                                                                                                                                                     
    D = np.diag(np.diag(A))
    # Create upper-triangular  matrix from A                                                                                                                                                                                                                                                                                                                     
    U = np.triu(A,1)
    #initial guess
    x = np.zeros(3)
    #First iteration
    B_GS_times_x = np.dot(np.dot(-(np.linalg.inv(np.add(L,D))),U),x)
    b_GS = np.dot(np.linalg.inv(np.add(L,D)),b)
    x = np.add(B_GS_times_x,b_GS)
    #creating a list to count lately the number of iterations before reaching a stopping criteria
    list_1=[]
    list_1.append(x)
    #establish a base case accuracy
    acc=10
    #second and other iterations
    while acc >= stopping_criteria:
        #formula for checking out current accuracy: np.linalg.norm(np.add(np.dot(B_j,x),b_j)-x)/np.linalg.norm(x)
        #in function np.add we put values for formula B_GS+b_GS as np.add(B_GS,b_GS) 
        acc = np.linalg.norm(np.add(np.dot(np.dot(-(np.linalg.inv(np.add(L,D))),U),x),np.dot(np.linalg.inv(np.add(L,D)),b))-x)/np.linalg.norm(x)
        x = np.add(np.dot(np.dot(-(np.linalg.inv(np.add(L,D))),U),x),np.dot(np.linalg.inv(np.add(L,D)),b))
        list_1.append(x)
    num_iter = len(list_1)
    print('Number of iteration to achieve 0.001 accuracy: ', num_iter)
    print('Found solution is vector: ', x)
    return x, num_iter

In [261]:
for 𝛼 in (2,3,4):
    print('For Alpha coefficient: ', 𝛼)
    gauss_seidel(𝛼,uuT,b)
    print('')

For Alpha coefficient:  2
Number of iteration to achieve 0.001 accuracy:  6
Found solution is vector:  [ 0.19997326 -0.1999872   0.20001318]

For Alpha coefficient:  3
Number of iteration to achieve 0.001 accuracy:  5
Found solution is vector:  [ 0.16664816 -0.16666032  0.16667288]

For Alpha coefficient:  4
Number of iteration to achieve 0.001 accuracy:  5
Found solution is vector:  [ 0.14285524 -0.14285533  0.14285788]



### (e) Write the corresponding iteration scheme for SOR using ω = 0.1 and ω = 1.1  method with $x_0=$*0*. How many iterations are required to achieve 0.001 accuracy? Test three different α in the convergence range. 

We will show that we can use the same convergence range for SOR as in (c) and (d). In (b) we established only convergence for Jacobi and Gauss-Seidel methods. But here in SOR we don't need to refer to spectral radius or norm. If A is symmetric and positive definite, then the SOR method is convergent iff 0 < ω < 2. Our ω is in this interval. A is symmetric. Let's check for which $\alpha$ A is positive definite. In our case we clearly see from:

$
A
=
\begin{pmatrix}α+1&-1&1\\ -1&α+1&-1\\ 1&-1&α+1\end{pmatrix}\\
$

that principal minors $D1$ and $D2$ are both $>0$ for $\alpha>1$. For $D3>0$ we have:

$
\det \begin{pmatrix}α+1&-1&1\\ -1&α+1&-1\\ 1&-1&α+1\end{pmatrix}=α^3+3α^2
$

So, also $D3>0$ for $\alpha>1$. So we can use the same convergence range for SOR ($\alpha>1$):

In [102]:
def SOR(ω,𝛼,uuT,b,stopping_criteria=0.001):
    """Solves equation Ax=b via the Gauss-Seidel iterative method,where
    𝛼 - parameter alpha of Problem 2 (;
    uuT - outer product of u;
    Instruction:
    we will perform first iteration and other iterations separately,
    because we can't divide by the norm of x_0 as it is a zero vector. Other 
    iterations will be perform via 'while' loop using base case accuracy of 10.
    """
    print('ω is',ω)
    # Create matrix A from sum of matrix 𝛼I and matrix uu^T (𝛼I + uu^T)
    alpha_times_identity = np.array([[α,0,0],[0,α,0],[0,0,α]])
    A = np.add(alpha_times_identity,uuT)
    # Create lower-triangular  matrix from A                                                                                                                                                                                                                                                                                                                     
    L = np.tril(A,-1)
    # Create diagonal  matrix from A                                                                                                                                                                                                                                                                                                                     
    D = np.diag(np.diag(A))
    # Create upper-triangular  matrix from A                                                                                                                                                                                                                                                                                                                     
    U = np.triu(A,1)
    #function definions of B_SOR * x and b_SOR to use in iterations:
    def B_SOR_times_x():
        return np.dot((np.dot((np.linalg.inv(np.add(D,ω*L))),(np.subtract(((1 - ω)*D),(ω*U))))),(x))
    def b_SOR():
        return ω*np.dot(np.linalg.inv(np.add(D,ω*L)),b)
    #initial guess
    x = np.zeros(3)
    #First iteration
    x = np.add(B_SOR_times_x(),b_SOR())
    #creating a list to count lately the number of iterations before reaching a stopping criteria
    list_1=[]
    list_1.append(x)
    #establish a base case accuracy
    acc=10
    #second and other iterations
    while acc >= stopping_criteria:
        #formula for checking out current accuracy: np.linalg.norm(np.add(np.dot(B_SOR,x),b_SOR)-x)/np.linalg.norm(x)
        #in function np.add we put values for formula B_SOR+b_SOR as np.add(B_GS,b_GS) 
        acc = np.linalg.norm(np.add(B_SOR_times_x(),b_SOR())-x)/np.linalg.norm(x)
        x = np.add(B_SOR_times_x(),b_SOR())
        list_1.append(x)
    num_iter = len(list_1)
    print('Number of iteration to achieve 0.001 accuracy: ', num_iter)
    print('Found solution is vector: ', x)
    return x, num_iter

In [103]:
for ω in (0.1,1.1):
    print('For ω coefficient: ', ω)
    for 𝛼 in (2,3,4):
        print('For Alpha coefficient: ', 𝛼)
        SOR(ω,𝛼,uuT,b)
    print('')

For ω coefficient:  0.1
For Alpha coefficient:  2
ω is 0.1
Number of iteration to achieve 0.001 accuracy:  31
Found solution is vector:  [ 0.20042935 -0.19916538  0.19787467]
For Alpha coefficient:  3
ω is 0.1
Number of iteration to achieve 0.001 accuracy:  33
Found solution is vector:  [ 0.16637071 -0.16577716  0.16517074]
For Alpha coefficient:  4
ω is 0.1
Number of iteration to achieve 0.001 accuracy:  35
Found solution is vector:  [ 0.14237259 -0.14204831  0.14171727]

For ω coefficient:  1.1
For Alpha coefficient:  2
ω is 1.1
Number of iteration to achieve 0.001 accuracy:  6
Found solution is vector:  [ 0.20002803 -0.20002751  0.19998824]
For Alpha coefficient:  3
ω is 1.1
Number of iteration to achieve 0.001 accuracy:  6
Found solution is vector:  [ 0.16665453 -0.16666676  0.16667026]
For Alpha coefficient:  4
ω is 1.1
Number of iteration to achieve 0.001 accuracy:  6
Found solution is vector:  [ 0.14285582 -0.14285454  0.14285712]



## Problem 4

### (a) Realize the power method to find the dominating eigenvalue of A and the corresponding eigenvector.

If $\lambda_1$ is an eigenvalue of $A$  that is larger in absolute value than any  other eigenvalue, it is called the dominant eigenvalue. An eigenvector $v_1$ corresponding to $\lambda_1$ is called a dominant eigenvector.
if $A$ is an $n×n$ matrix with $n$ distinct eigenvalues $λ1,λ2,...,λn$ for which one is dominating, say $λ_1$ such that $∣λ1∣>∣λ2∣>...>∣λn∣$, then we could approximate the eigenvalue $λ_1$ iteratively.Formula for matrix $A$:
$$
x=x_0=some-non-zero-vector.\\
while:\\ 
epsilon < convergence-criteria:\\
    p = A x;\\
    max-entry-of-p = max(map(abs, p));\\
    x = \frac{p}{max-entry};
$$ 
From Youssef Saad's book Numerical Methods for Large Eigenvalue Problems, 2nd edition we can use the norm of the residual vector r to define convergence criteria of power method:
$$
r = |Ax -\lambda x|\\
‖r‖<𝜀
$$

In [134]:
#Diagonal matrix D
D = np.diagflat([[1,2], [3,4],[5,6],[7,8],[9,10]])
print(D)

[[ 1  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0]
 [ 0  0  0  4  0  0  0  0  0  0]
 [ 0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  6  0  0  0  0]
 [ 0  0  0  0  0  0  7  0  0  0]
 [ 0  0  0  0  0  0  0  8  0  0]
 [ 0  0  0  0  0  0  0  0  9  0]
 [ 0  0  0  0  0  0  0  0  0 10]]


In [135]:
#seed to get reproducable results for random matrix generation
np.random.seed(0)
#let's constrain our random metrix P entries to range(0,10)
P = np.random.random_integers(0, 10, (10,10))
print(P)

[[ 5  0  3  3  7  9  3  5  2  4]
 [ 7  6  8  8 10  1  6  7  7  8]
 [ 1  5  9  8  9  4  3  0  3  5]
 [ 0  2  3  8  1  3  3  3  7  0]
 [ 1  9  9  0 10  4  7  3  2  7]
 [ 2  0  0  4  5  5  6  8  4  1]
 [ 4  9 10 10  8  1  1  7  9  9]
 [ 3  6  7  2  0  3  5  9 10  4]
 [ 4  6  4  4  3  4  4  8  4  3]
 [10  7  5  5  0  1  5  9  3  0]]


/home/alexus/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: DeprecationWarning: This function is deprecated. Please call randint(0, 10 + 1) instead
  after removing the cwd from sys.path.


In [136]:
#Let's find inverse of P:
P_inverse = np.linalg.inv(P)
print(P_inverse)

[[ 0.15033915  0.02591513 -0.20908849  0.15042663  0.1070685  -0.09673381
   0.06265476 -0.07786602 -0.22280322  0.12365779]
 [ 0.07266546 -0.094607   -0.31374845  0.27212391  0.24737708 -0.09614919
   0.15274493 -0.1873245  -0.0753201   0.08098657]
 [-0.08590151 -0.11048329  0.36153976 -0.29976706 -0.1467455   0.15290501
  -0.01845919  0.2143909  -0.13244793  0.06427421]
 [-0.11296805  0.16679967  0.2167197  -0.06137479 -0.21002996 -0.08980167
  -0.19507281  0.00149386  0.44785589 -0.14454577]
 [ 0.13977865 -0.29066834 -0.30666424  0.15602697  0.32339227  0.26258918
   0.4066025  -0.15467492 -0.75583487  0.26548329]
 [ 0.11232458 -0.02987543 -0.04131403  0.09875621  0.02596522 -0.10438845
  -0.03601865 -0.02322913  0.11199718 -0.03625959]
 [-0.13625145  0.30248293  0.18210609 -0.0399124  -0.14277444 -0.13471498
  -0.37401335  0.07288839  0.47443819 -0.18263895]
 [-0.11084712 -0.1019352   0.19640829 -0.27886686 -0.13466767  0.22221575
   0.04711096  0.10202589  0.05506144  0.00468426]


In [137]:
# setting A = P DP^−1
A = np.dot(P,np.dot(D,P_inverse))
print(A)

[[  0.10498837   7.99322492   7.36058448  -5.90908672  -8.16536431
   -3.75250514  -9.52923944   3.71444802  23.54891433 -11.03897697]
 [ -7.44086383  22.75956395   9.95038736  -8.72978804 -14.19517672
   -7.18093568 -16.9877912    7.48670404  35.80849474 -19.42488941]
 [ -0.83523337  13.78444953   5.31520881   0.34323417  -6.09688943
   -9.64271391 -11.35594456   1.54042225  21.61734837 -11.69147534]
 [  4.62764694  -3.43632917 -10.86740342  12.60422522   7.31273194
    2.21664733   6.79725405  -1.21189372 -15.47213992   3.83726709]
 [ -6.79883565  23.10554641  13.51361482  -9.6029783  -12.89623314
  -11.87178473 -23.15013389   6.81009061  42.67971884 -20.21670705]
 [ -2.24155572   0.17229852   2.28951693  -3.27310079  -1.94129418
    8.15172261  -1.05090905   3.08470344   2.89898483  -2.12963924]
 [ -3.57932858  17.20130885   4.66509305  -5.97587812 -12.16192018
   -8.01164241  -8.47618682   6.57324567  28.83972021 -17.61662777]
 [ -1.12069953   6.38829633  -1.24506117  -0.62244533  

In [138]:
np.diag(D)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [173]:
eigs,_ = np.linalg.eig(A)

In [174]:
#look at eigenvalues
eigs

array([ 1., 10.,  9.,  2.,  3.,  8.,  4.,  7.,  5.,  6.])

In [161]:
def power_method(A,shape=2,epsilon=0.001):
    #generate non-zero vector x with 1 at 1st row 1st col to use it in iteration:
    x = list(np.zeros(shape))
    x[0] = 1
    x = np.array(x)
    list_max_entries = []
    #first iteration
    p = np.dot(A,x)
    max_entry = max(map(abs, p))
    x = p / max_entry
    list_max_entries.append(max_entry)
    #second and other iterations
    while abs(np.linalg.norm(np.dot(A,x)) - np.linalg.norm(max_entry*x)) >= epsilon: 
        p = np.dot(A,x)
        max_entry = max(map(abs, p))
        x = p / max_entry
        list_max_entries.append(max_entry)
    #let's round to integer value both dominant eigenvalue and every entry in corresponding eigenvector
    #x = np.round(x)
    #max_entry = round(max_entry)
    print('Dominant eigenvalue:',max_entry)
    print('Corresponding eigenvector:')
    print(x/np.linalg.norm(x))
    print('')
    print('Number of iterations:',len(list_max_entries)-1)
    return x/np.linalg.norm(x),max_entry,list_max_entries
    

In [162]:
x, dom_eigenvalue,list_max_entries_A = power_method(A,shape=10,epsilon=0.0001)

Dominant eigenvalue: 10.00026293089925
Corresponding eigenvector:
[-2.47616118e-01 -4.95188291e-01 -3.09512820e-01  1.02532255e-04
 -4.33350175e-01 -6.18527663e-02 -5.57070348e-01 -2.47498938e-01
 -1.85675472e-01  4.39380203e-05]

Number of iterations: 81


**Solution** We have found dominant eigenvalue (rightly corresponds to the largest value in diagonal matrix D) and corresponding eigenvector.

### (b) Apply the inverse power method to find several (e.g. 4) other eigenvalues and the corresponding eigenvectors. To that end, determine the range in which one should search for the remaining eigenvalues, and then try several random approximations λ.

Let's choose initial x as a vector of all ones:

In [203]:
x = np.ones(10)

Formula for inverse power method (shifted) is the following (from https://en.wikiversity.org/wiki/Shifted_inverse_iteration).

Iterate until $c_k$ converges (diff.between successive approximations is minimal): 

$
B = (A - \alpha I)^{-1}
$

$
y_{k} = Bx_{k-1}
$

$
c_k = \frac{y_{k}^T x_{k-1}}{x_{k-1}^T x_{k-1}}
$

$
x_k = \frac{y_{k}}{\norm{y_{k}}}
$

,where first $x_k$ would be initial guess vector and $\lambda$ would be initial guess eigenvalue.

After convergence of $c_k$ our eigenvalue would be:

$
\lambda = \frac{1}{c_k} + \alpha
$

Eigenvector $v$ would be the last $x_k$.

Let's write function for inverse power method:

In [219]:
def inv_power_shift(A,guess,x,epsilon=0.0001):
    """
    A is our input matrix
    guess is our good guess for eigenvalue
    x is our initial x
    epsilon to know when to end interation
    """
    a=A-guess*np.identity(A.shape[0])
    b=np.linalg.inv(a)
    y=np.dot(b,x)
    c=(np.dot(y,x))/(np.dot(x,x))
    candidates=[c]
    c_new = c*2
    x = y/np.linalg.norm(y)
    eig_vectors = [x]
    candidates.append(c_new)
    while np.abs(candidates[-1]-candidates[-2])>epsilon:
        eig_vectors.append(x)
        y=np.dot(b,x)
        c=(np.dot(y,x))/(np.dot(x,x))
        candidates.append(c)
        x = y/np.linalg.norm(y)
    return 1/c+guess,eig_vectors[-1]

Given that eigenvalues of A are 1,2,3,...,10, we will use similar initial guesses in loop:

In [220]:
for guess in [1.1,1.9,2.8,4.1,5.2,6.1,6.8,7.9,9.1,10.1]:
    ev,eigvect = inv_power_shift(A,guess,x,epsilon=0.0001)
    print('Approxim.Eigenvalue is:',ev)
    print('Corresponding.Eigenvector is:',eigvect)

Approxim.Eigenvalue is: 1.0000000928372466
Corresponding.Eigenvector is: [-3.36336678e-01 -4.70870984e-01 -6.72670312e-02  1.21806277e-07
 -6.72667877e-02 -1.34534671e-01 -2.69068794e-01 -2.01801642e-01
 -2.69068977e-01 -6.72672930e-01]
Approxim.Eigenvalue is: 2.000000028020169
Corresponding.Eigenvector is: [1.16503269e-07 3.21633842e-01 2.68028089e-01 1.07211227e-01
 4.82450540e-01 4.77308673e-08 4.82450611e-01 3.21633747e-01
 3.21633772e-01 3.75239525e-01]
Approxim.Eigenvalue is: 3.0000002690810463
Corresponding.Eigenvector is: [-1.44004453e-01 -3.84012238e-01 -4.32013662e-01 -1.44004573e-01
 -4.32013904e-01  4.03466171e-10 -4.80015388e-01 -3.36010754e-01
 -1.92006300e-01 -2.40007845e-01]
Approxim.Eigenvalue is: 4.000000045602787
Corresponding.Eigenvector is: [-1.57676376e-01 -4.20470572e-01 -4.20470598e-01 -4.20470810e-01
  2.66217395e-07 -2.10235285e-01 -5.25588335e-01 -1.05117709e-01
 -2.10235338e-01 -2.62794273e-01]
Approxim.Eigenvalue is: 5.000000737152379
Corresponding.Eigenvec

**Conclusion:**

As we see, inverse power method worked well in approximating true eigenvalues.

## Problem 5

### (a) With the matrix D of the above problem, form $A = D + uu^T$ with $u$ being a random vector of size 10. Realize the QR algorithm to find the eigenvalues and eigenvectors of $A$.

In [237]:
np.random.seed(123)

u = np.random.rand(10, 1)

A = D + u.dot(u.T)

In [238]:
def QR_method(A):
    #eigenvectors matrix
    EVect = np.eye(len(A))
    for i in range(50):
        Q, R = np.linalg.qr(A)
        A = np.dot(R, Q)
        EVect = EVect.dot(Q)
    return np.diag(A), EVect

In [239]:
eigvals,eigvects = QR_method(A)
print("Eigenvalues from QR method in 50 iterations are: ")
print(eigvals)
print('')
print("Eigenvectors from QR method in 50 iterations are: ")
print(eigvects)

Eigenvalues from QR method in 50 iterations are: 
[10.7552765   9.5773636   8.61778455  7.54808565  6.10341375  5.30631735
  4.15167321  3.02999974  2.06280537  1.2822314 ]

Eigenvectors from QR method in 50 iterations are: 
[[ 0.09989687  0.05848652  0.04964943  0.04379501  0.03525637 -0.06126254
  -0.05853951 -0.04507244 -0.14146833 -0.97557628]
 [ 0.04573034  0.02720473  0.02348747  0.02123949  0.01808999 -0.032825
  -0.03522761 -0.036496   -0.98353966  0.15760056]
 [ 0.04093081  0.02485292  0.02194447  0.0205458   0.01911048 -0.03738878
  -0.05217555 -0.9934091   0.05225439  0.05220854]
 [ 0.11420241  0.07125283  0.06491886  0.0640273   0.06986304 -0.16105366
  -0.96279115  0.07466565  0.06143805  0.08019583]
 [ 0.1749375   0.11335604  0.10823911  0.11641797  0.19930808 -0.91114862
   0.224525    0.04797929  0.05287987  0.0765058 ]
 [ 0.12452009  0.08536929  0.08813074  0.11305672  0.93290366  0.28376669
   0.06066035  0.01871544  0.02319924  0.03545501]
 [ 0.36554347  0.27516019  

### (b) Then apply the power method to find the dominating eigenvalue and the corresponding eigenvector and compare the results.

Using custom function from Problem 4:

In [242]:
x, dom_eigenvalue,list_max_entries_A = power_method(A,shape=10,epsilon=0.0001)

Dominant eigenvalue: 10.755346233060076
Corresponding eigenvector:
[0.09979694 0.04568386 0.04088836 0.11408071 0.17474394 0.12437438
 0.36507425 0.34743959 0.38301455 0.7256509 ]

Number of iterations: 79


**Conclusion**

As we see, results from two methods for dominant eigenvalue/eigenvector are pretty similar.

## Problem 3

### (a) Solve Ax=b of Problem 1 by Conjugate gradient method: identify the conjugate gradients and the iteration steps? 

$$
A = 
\begin{pmatrix}2&-1&0\\ -1&2&-1\\ 0&-1&2\end{pmatrix};
b =
\begin{pmatrix}1\\ 0\\ 1\end{pmatrix}.
$$

GCM procedure is the next:

Step 1. Choose $x_0$ and $\epsilon$. Set $p_0=r_0=b-Ax_0$.

Step 2. For i = 0,1,2,3..do:
$$
w = Ap_i;\\
a_i = \frac{| r_i |^{2}}{p_i^Tw}\\
x_{i+1} = x_i +a_i p_i\\
r_{i+1} = r_i - a_i w.\\
$$


$
|r_{i+1}|^{2} >= \epsilon
\rightarrow
\\
\rightarrow
\beta = \frac{|r_{i+1}|^{2}}{|r_{i}|^{2}}\\
p_{i+1} = r_{i+1} + \beta p_i.
$

In [127]:
A = np.array([[2,-1,0],[-1,2,-1],[0,-1,2]])
b = np.array([1,0,1])

In [132]:
def GCM(A,b,stopping_criteria=0.001):
    #setting down base accuracy and initial x_0 and p_0=r_0=b-Ax_0
    acc=10
    x = np.zeros(3)
    p = np.subtract(b,np.dot(A,x))
    list_conjugates = []
    list_conjugates.append(p)
    #create list to save number of x vectors
    list_1 = []
    #iteration
    while acc>=stopping_criteria:
        w = np.dot(A,p)
        a = np.dot(p,p) / np.dot(p,w)
        x = x+a*p
        list_1.append(x)
        r = p - a*w  
        beta = np.dot(r,r) / np.dot(p,p)
        list_conjugates.append(p)
        p = r + beta*p
        acc = np.dot(r,r)
    num_iter = (len(list_1))
    print('Solution vector is', x)
    print('Number of iterations is',num_iter)
    print('List of conjugate vectors p is saved in list_conjugates' )
    return x,num_iter,list_conjugates
    

In [129]:
x,num_iter,list_conjugates = GCM(A,b)

Solution vector is [4.88121368 5.85745642 4.88121368]
Number of iterations is 26
List of conjugate vectors p is saved in list_conjugates


### (b) Solve Ax=b of Problem 2 by Conjugate gradient method (𝛼=1): identify the conjugate gradients and the iteration steps? 

$
b = u =
\begin{pmatrix}1\\ -1\\ 1\end{pmatrix}\\
uu^T = 
\begin{pmatrix}1&-1&1\\ -1&1&-1\\ 1&-1&1\end{pmatrix}\\
A=
\begin{pmatrix}α+1&-1&1\\ -1&α+1&-1\\ 1&-1&α+1\end{pmatrix}
$

In [267]:
u = np.array([1,-1,1])
uuT = np.outer(b,b)
b = u
alpha_times_identity = np.array([[1,0,0],[0,1,0],[0,0,1]])
A = np.add(alpha_times_identity,uuT)

In [268]:
x,num_iter,list_conjugates = GCM(A,b)

Solution vector is [ 0.39359666 -1.31639244  0.39359666]
Number of iterations is 5
List of conjugate vectors p is saved in list_conjugates
